### ISSUE TITLE
Find a better solution for the custom JRE

### ISSUE THREAD

**Issue by LennysLounge** [LennysLounge/ACC-Race-Control#1]
Currently the JRE is part of the src directory and gets copied into the distribution. That is not very nice because it makes the src directory bigger than it need to be.

A better solution would be to create the JRE dynamicly when building a distribution.

**Comment by bradfier** [comment]
I'm absolutely not a Java expert, but since the goal here is a simple `.exe` anyone can run on their PC beside ACC, could something like GraalVM work? 

https://www.graalvm.org/reference-manual/native-image/
