### ISSUE TITLE
Bug: Mass crashes or leaving the session lead to faulty replays

### ISSUE THREAD

**Issue by schmedia-dev** [LennysLounge/ACC-Race-Control#16]
As mentioned in another issue, we had a mass crash, which caused some drivers to leave the race immediately.
As a result, we had a mess of replays in the app. Unfortunately, we don't know whether it was due to the mass crash (too many contacts in a very short time) or the driver leaving the session.

**Comment by schmedia-dev** [comment]
Sorry for the bad description
When we clicked on a vehicle number, the wrong scenes sometimes came up or scenes ended too early, which is why we had no contact or only until shortly before the contact

**Comment by LennysLounge** [comment]
When there are a lot of crashes happening at the same time it is very difficult to process the game data correctly.
This will cause the replay button to show the wrong cars in that moment. There really isnt anything i can do about this until the game outputs better data.
