### ISSUE TITLE
After Start the splash screen is visible but no further action

### ISSUE THREAD

**Issue by Doprintityourself** [LennysLounge/ACC-Race-Control#20]
I modified the broadcast.json and start the tool
i can see short splash of the start icon  but the tool never gets further I do not see the tool afterwards.
Tried with a server or acc running nothing

**Comment by LennysLounge** [comment]
If you could post the log files when the error occurs then maybe i can help

**Comment by Doprintityourself** [comment]
as I did not find the logs nor any information where to find ( seems my fault) I searched the internet and came over another version 1.5.5 from race department downloaded it and it worked. the difference was the first was the github zip downloaded from this side did not work.
